backend:
  name: git-gateway
  # test-repo
  # git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: 'main'
    label: 'Main'
    folder: 'src/pages/main'
    create: true
    slug: { { 'slug' } }
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'home-page',
        }
      - { label: Slug, name: slug, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Heading, name: heading, widget: string }
      - { label: Subheading, name: subheading, widget: string }
      - {
          label: Offerings,
          name: offerings,
          widget: object,
          fields:
            [
              {
                label: Blurbs,
                name: blurbs,
                widget: list,
                fields:
                  [
                    { label: Image, name: image, widget: image },
                    { label: Slug, name: slug, widget: string },
                    { label: Name, name: name, widget: string },
                    { label: Text, name: text, widget: text },
                  ],
              },
            ],
        }
      - {
          label: Partners,
          name: partners,
          widget: object,
          fields:
            [
              {
                label: Logo,
                name: logo,
                widget: list,
                fields: [{ label: Image, name: image, widget: image }],
              },
            ],
        }
      - {
          label: Quote,
          name: quote,
          widget: object,
          fields:
            [
              { label: Text, name: text, widget: text },
              { label: Name, name: name, widget: string },
              { label: Title, name: title, widget: string },
            ],
        }
      - {
          label: Advantage,
          name: advantages,
          widget: object,
          fields:
            [
              {
                label: Blurbs,
                name: blurbs,
                widget: list,
                fields:
                  [
                    { label: Image, name: image, widget: image },
                    { label: Text, name: text, widget: text },
                  ],
              },
            ],
        }
      - { label: 'Meta Title', name: meta_title, widget: string }
      - { label: 'Meta Description', name: meta_description, widget: text }
  - name: 'about'
    label: 'About'
    folder: 'src/pages/about'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'product-page',
        }
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: 'Nav Logo', name: nav_logo, widget: string }
      - { label: Heading, name: heading, widget: string }
      - { label: Subheading, name: subheading, widget: string }
      - { label: 'Heading Image', name: heading_image, widget: image }
      - { label: 'Hero Image', name: hero_image, widget: image }
      - { lable: Ingredients, name: ingredients, widget: text }
      - {
          label: Analysis,
          name: analysis,
          widget: object,
          fields:
            [
              {
                label: 'Content',
                name: content,
                widget: list,
                fields,
                [{ label: Text, name: text, widget: string }],
              },
            ],
        }
      - {
          label: Advantages,
          name: advantages,
          widget: object,
          field:
            [
              {
                label: Icon,
                name: icon,
                widget: list,
                fields: [{ label: Image, name: image, widget: image }],
              },
            ],
        }
      - {
          label: Partners,
          name: partners,
          widget: object,
          field:
            [
              {
                label: Icon,
                name: icon,
                widget: list,
                fields: [{ label: Image, name: image, widget: image }],
              },
            ],
        }
      - {
          label: Quote,
          name: quote,
          widget: object,
          fields:
            [
              { label: Text, name: text, widget: text },
              { label: Name, name: name, widget: string },
              { label: Title, name: title, widget: string },
            ],
        }
      - { label: 'Meta Title', name: meta_title, widget: string }
      - { label: 'Meta Description', name: meta_description, widget: text }
